# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-14 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Neighborhood',
            new_name='Neighboorhood',
        ),
    ]
